// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpYoeJ-hGg2uz0ITlNXZ_5BmvWu1D_c0',
    appId: '1:799981520759:web:ee80c01b183abfae1c8372',
    messagingSenderId: '799981520759',
    projectId: 'handinet-1058d',
    authDomain: 'handinet-1058d.firebaseapp.com',
    storageBucket: 'handinet-1058d.firebasestorage.app',
    measurementId: 'G-0TCZYX1ZJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5OzGOhgp_5z8sgXt6zd4b4JLO2FyyRzw',
    appId: '1:799981520759:android:18fe639f9a646c8e1c8372',
    messagingSenderId: '799981520759',
    projectId: 'handinet-1058d',
    storageBucket: 'handinet-1058d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1kj2JnE3I4_N_bUoIwvKC7qNrH0CV-o',
    appId: '1:799981520759:ios:0ebeeb2c2a2d03321c8372',
    messagingSenderId: '799981520759',
    projectId: 'handinet-1058d',
    storageBucket: 'handinet-1058d.firebasestorage.app',
    iosBundleId: 'com.example.handiNetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1kj2JnE3I4_N_bUoIwvKC7qNrH0CV-o',
    appId: '1:799981520759:ios:0ebeeb2c2a2d03321c8372',
    messagingSenderId: '799981520759',
    projectId: 'handinet-1058d',
    storageBucket: 'handinet-1058d.firebasestorage.app',
    iosBundleId: 'com.example.handiNetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfpYoeJ-hGg2uz0ITlNXZ_5BmvWu1D_c0',
    appId: '1:799981520759:web:e8de49fbbfdda1071c8372',
    messagingSenderId: '799981520759',
    projectId: 'handinet-1058d',
    authDomain: 'handinet-1058d.firebaseapp.com',
    storageBucket: 'handinet-1058d.firebasestorage.app',
    measurementId: 'G-3EP5TFEBEE',
  );
}
